### PR TITLE
[FIX] Update maintainer-tools, fix TravisCI builds

### PR DESCRIPTION
**Pull request by dreispt**
As per https://github.com/OCA/oca-addons-repo-template/pull/44#issuecomment-743046947

### CODE REVIEW

**Comment by sbidoul** [comment]
@dreispt this one is incomplete: it removed the lint step from travis but did not add the GitHub workflow (.github/workflows directory). Either the copier command did not work or you forgot to commit the new files ?

**Comment by dreispt** [comment]
Hmm, I did leave out a `.github` directory. Let me fix that.

**Comment by dreispt** [comment]
@sbidoul Thanks for checking

**Comment by sbidoul** [comment]
Merged manually because GitHub actions do not trigger when the workflow files are added from a fork (not entirely sure about how that works exactly). The checks are working on the 14.0 branch: https://github.com/OCA/account-fiscal-rule/runs/1537570522

**Comment by dreispt** [comment]
What do you recomemend for next time: should I commit directly to 14.0 or create PR and merge manually?

**Comment by dreispt** [comment]
BTW, confirmation that it is working: https://github.com/OCA/account-fiscal-rule/pull/160

**Pull request merged**
