### PR TITLE
Separated Lint tests

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by yvaucher** [comment]
Few pylint error to fix

**Comment by pedrobaeza** [comment]
Remove travis_run_flake8 line

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lepistone** [comment]
It duly tells us that lint is red. Can we can take the occasion to make it green here?

Once done, :+1: thanks!

**Comment by yvaucher** [comment]
@lepistone done

**Comment by lepistone** [comment]
thanks!

**Comment by rvalyi** [comment]
:+1:

**Pull request merged**
