### PR TITLE
[8.0] [MIG] l10n_eu_oss: Backport to 8.0

### PR DESCRIPTION
**Pull request by RodrigoBM**
add cherry pick #207

Issue: OCA/l10n-spain#1718

### CODE REVIEW

**Comment by RodrigoBM** [comment]
Apply rebase this PR https://github.com/OCA/account-fiscal-rule/pull/228 merged to 8.0

**Comment by RodrigoBM** [comment]
Hi @pedrobaeza ,

if this module was added https://github.com/OCA/account-fiscal-rule/pull/228, I think it would be good to let this PR be approved as well.

Best regards

**Comment by pedrobaeza** [comment]
I will as soon as possible.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
