### PR TITLE
Feature/account fiscal position rule migration 8.0

### PR DESCRIPTION
**Pull request by renatonlima**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, Renato, thanks for the migration. There are PEP8 issues regarding this module:

```
./account_fiscal_position_rule/account_fiscal_position_rule.py:39:9: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:42:9: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:48:9: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:57:9: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:59:9: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:61:13: E126 continuation line over-indented for hanging indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:65:9: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:66:9: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:68:9: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:79:17: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:80:17: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:87:17: E126 continuation line over-indented for hanging indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:92:17: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:99:17: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:102:17: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:120:9: E265 block comment should start with '# '
./account_fiscal_position_rule/account_fiscal_position_rule.py:125:9: E265 block comment should start with '# '
./account_fiscal_position_rule/account_fiscal_position_rule.py:136:81: E501 line too long (81 > 80 characters)
./account_fiscal_position_rule/account_fiscal_position_rule.py:143:9: E265 block comment should start with '# '
./account_fiscal_position_rule/account_fiscal_position_rule.py:169:9: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:182:9: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:184:9: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:190:9: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:191:9: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:193:9: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_fiscal_position_rule.py:201:9: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_invoice.py:48:13: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule/account_invoice.py:61:13: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule_purchase/purchase.py:58:33: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule_purchase/purchase.py:59:33: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule_stock/stock.py:61:12: E121 continuation line under-indented for hanging indent
./account_fiscal_position_rule_stock/stock.py:72:13: E128 continuation line under-indented for visual indent
./account_fiscal_position_rule_stock/stock.py:74:9: E122 continuation line missing indentation or outdented
```

Can you please fix them?

**Comment by pedrobaeza** [comment]
Another problem is that this repository is not properly set, moving all modules to `__unported__` dir before any work, so tests are not reliable now. We have two options:
- Let me create a 8.0 branch, and move all modules to `__unported__`, and you recreate the 4 PRs against this branch.
- Merge this PRs in a blind way, and then switch to 8.0.

I prefer option 1, but this implies a little more work for your part. What do you say?

Regards.

**Comment by rvalyi** [comment]
Hello Pedro, well we prefer option 2 because working in 8.0 sends the message that this is stable work while in our opinion this is not yet because we will still authorize us non backward compatible changes for a few weeks to take advantage of the major release window.

As a reviewer we can still ensure that failing tests aren't in the modules submitted for merges.

Now, the test fails because of the absence of the web_context_tunnel dependency (new dependency). I'll propose it for merge in master or v8 and then we will be able to rebase these 4 fiscal rules merges with a proper repo dependency to web_context_tunnel.

Also eventually we also find some time to add some tests and rebase with some tests, but that is not guaranteed we have time for this (as for us we do test most of the features in or localization), so if somebody using fiscal rules can help submitting tests this is always welcome.

So sorry we didn't sort out the web_context_tunnel dep yet. I'll do that soon, sorry for the inconvenience.

**Comment by pedrobaeza** [comment]
OK then, but please fix also PEP8 issues.

Regards.

**Comment by renatonlima** [comment]
Hi guys, thanks for your feedback

@pedrobaeza 

I will fix PEP8 issues.

IMHO think we can migrate all modules in master branch and after freeze master branch in new branch 8.0. What do you think?

**Comment by pedrobaeza** [comment]
Ok, let's do it this way, but as you are making partials PRs, we are not getting correct feedback from Travis.

**Comment by guewen** [comment]
According to the migration dashboard, this project has not been migrated to GitHub yet (or not been finalized): https://docs.google.com/spreadsheets/d/1CfGY7rc60jnpAWvMfNf0pI7fBDAlumwI2jx6f_RJ4_4/edit?pli=1#gid=0

Is the spreadsheet accurate? If the project still needs to be migrated, may one of you complete the migration?

**Comment by gurneyalex** [comment]
@renatonlima please resubmit on branch 8.0

**Comment by renatonlima** [comment]
Hello @gurneyalex 

I will resubmit my branch on 8.0

**Pull request closed without merging**
