### PR TITLE
[14.0] [IMP] acc_fisc_classif: add chatter on categ and log tax m2m

### PR DESCRIPTION
**Pull request by bealdav**
cc @legalsylvain could you evaluate it, please ?

For the futur I suppose we could use this one https://github.com/OCA/server-tools/pull/2434

But now we can merge as it, I suppose

### CODE REVIEW

**Comment by bealdav** [comment]
FIX https://github.com/OCA/account-fiscal-rule/issues/344

**Comment by legalsylvain** [comment]
Tested on runboat. LGTM.

Tecnically, I was asking to me if it was not interesting to create a dedicated module name tracking_x2x with something generic. What do you think ? (can be done in a second step)

image

**Comment by bealdav** [comment]
Yes you're right, it should be done in a separate helper module.
In a second step yes. We should go for v16 for that ?

**Comment by LESTRAT21** [comment]
Hello, I tested via runboat. This module is suppose to add a chatter in the fiscal classification view, isn't it ? I cannot see the chatter.
image
 I did something wrong  ?

**Comment by LESTRAT21** [comment]
I didn't tested non the right runboat. My functionnal test is ok : in the chatter, the taxes added in the the classification category are listed.
image

**Review by LESTRAT21 — APPROVED** [review]

**Comment by sebastienbeau** [comment]
@legalsylvain @LESTRAT21 the module tracking_manager is ready for V14, already used in production (all m2m can be tracked)

**Comment by legalsylvain** [comment]
@sebastienbeau : where is the module tracking_manager ?

**Pull request closed without merging**
