### PR TITLE
[15.0][MIG] account_avatax

### PR DESCRIPTION
**Pull request by dnplkndll**

### CODE REVIEW

**Comment by dnplkndll** [comment]
@dreispt 
I think I need a hand here. python3.6 to python3.8 the Avalera module seems to be spec'ed like others and installs fine on my env. Is there something I am missing here? 

It looks like we are building on 
```
Step 1/22 : FROM vauxoo/odoo-80-image-shippable-auto
latest: Pulling from vauxoo/odoo-80-image-shippable-auto
Digest: sha256:474a6205dea6e597879259ab6f50fb282c8ce1ed9f4d9aa1fa56399f784f797b
Status: Image is up to date for vauxoo/odoo-80-image-shippable-auto:latest
```
https://hub.docker.com/r/vauxoo/odoo-80-image

should the base be(?):
https://hub.docker.com/r/vauxoo/odoo-150-image

https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo150/Dockerfile 

I can probably recreate this test env, but perhaps missing something simple?

```
Step 21/22 : RUN /bin/bash -c "source ${REPO_REQUIREMENTS}/virtualenv/python3.8/bin/activate && source ${REPO_REQUIREMENTS}/virtualenv/nodejs/bin/activate && source /rvm_env.sh && /install"
 ---> Running in b7daa76ecc6f
[91m/bin/bash: /.repo_requirements/virtualenv/python3.8/bin/activate: No such file or directory
[0mThe command '/bin/sh -c /bin/bash -c "source ${REPO_REQUIREMENTS}/virtualenv/python3.8/bin/activate && source ${REPO_REQUIREMENTS}/virtualenv/nodejs/bin/activate && source /rvm_env.sh && /install"' returned a non-zero code: 1
```
versus
```
Step 21/22 : RUN /bin/bash -c "source ${REPO_REQUIREMENTS}/virtualenv/python3.6/bin/activate && source ${REPO_REQUIREMENTS}/virtualenv/nodejs/bin/activate && source /rvm_env.sh && /install"
 ---> Running in d8b683e2f4d3
[91mCloning into '/home/odoo/maintainer-quality-tools'...
```

**Comment by dreispt** [comment]
@dnplkndll Not sure what is the issue you're seeing.
My dev box runs Python 3.8 so I can check if I have details.
OCA tests are green, though, so things look good there.

Regarding your particular container deployment, I'm not the best person to discuss.
Maybe @max3903 is more familiar with it and can help.

**Comment by dreispt** [comment]
PS: I see issue is with that build command. It looks like debugging is needed, and I'm not familiar with that environment to give advice at this point.

**Review by dreispt — APPROVED** [review]
Tested, needs minor fixes, done in #247

**Pull request closed without merging**
