### PR TITLE
[14.0] account_avatax: Add Avatax retail price

### PR DESCRIPTION
**Pull request by atchuthan**
cc: @SodexisTeam @dreispt

### CODE REVIEW

**Comment by dreispt** [comment]
Thank you @atchuthan 
I have concerns about the design for this feature:
I wonder if it is duplicating some Odoo features, and I'm not sure how it is expected to be used.

It would be helpful the have an explanation on how to use, and the how it works.
Ideally, you would add this into the proper readme fragments.

Thanks!

**Comment by dnplkndll** [comment]
@dreispt  would our next CO filing be useful to review? it just took effect this month so that will be after 8/1/22. all the US businesses with CO nexus would have this liability but might not be any others using Odoo?

**Comment by atchuthan** [comment]
> Thank you @atchuthan I have concerns about the design for this feature: I wonder if it is duplicating some Odoo features, and I'm not sure how it is expected to be used.
> 
> It would be helpful the have an explanation on how to use, and the how it works. Ideally, you would add this into the proper readme fragments.
> 
> Thanks!

Sure, we will add the info in readme fragments and publish the PR later

**Comment by osi-scampbell** [comment]
@atchuthan is there an update on this PR?

**Comment by atchuthan** [comment]
> @atchuthan is there an update on this PR?

We are currently using this fix for one of our customers in production.

**Comment by atchuthan** [comment]
> Thank you @atchuthan I have concerns about the design for this feature: I wonder if it is duplicating some Odoo features, and I'm not sure how it is expected to be used.
> 
> It would be helpful the have an explanation on how to use, and the how it works. Ideally, you would add this into the proper readme fragments.
> 
> Thanks!

@dreispt I don't think this is some duplicate of odoo features.  We are adding a new line based on config to SO line and Invoice line.

Sure, we will add the explanation in readme fragments in few days.

**Comment by cybernexus** [comment]
I'm trying to determine how this pull request works to satisfy the conditions set forth by Avalara? According to their information you must add a line item to sale / invoice for a product setup with the appropriate tax code and make the price for that line a $0.00 amount. I tried this in one of our staging environments. using this pull request, and it did not appear to work. As I read it, the line item should be added to sale / invoice and then multiple taxes should be applied. One a fixed tax of $0.27 and then others as well because you can have a tax on that $0.27 fee. I did some research and apparently this is not specific to the Colorado delivery fee. The avatax API allows for the ability to return mixed mode flat and percentage based tax rates in their response for any particular item line.    This should be patched as soon as possible because the side affect as of right now is that you could have a $1,000.00 line subject to a $20.00 flat rate fee but the avatax module sees it as a $200.00 fee. All tax rates get imported and converted to percentage regardless of the information stored in the "unitofBasis" field.

**Pull request closed without merging**
