### PR TITLE
Test pass

### PR DESCRIPTION
**Pull request by mileo**
FIX #37 #35 

Good night!

### CODE REVIEW

**Comment by mileo** [comment]
Any one knows why we have this message, the oca_dependencies.txt seems to be ok

File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3119407-38-da5905/openerp/addons/base/module/module.py", line 393, in state_update
    raise orm.except_orm(_('Error'), _("You try to install module '%s' that depends on module '%s'.\nBut the latter module is not available in your system.") % (module.name, dep.name,))
except_orm: ('Error', u"You try to install module 'account_fiscal_position_rule_purchase' that depends on module 'web_context_tunnel'.\nBut the latter module is not available in your system.")

**Comment by pedrobaeza** [comment]
Can you squash the commit history a bit?

I have added the dependency to runbot and restart the build.

**Comment by mileo** [comment]
@pedrobaeza Done

**Comment by pedrobaeza** [comment]
I still see 17 commits with very weak modifications like pep8 and so on. Please join also that.

**Comment by mileo** [comment]
@pedrobaeza You are talking about the Akretion's commits? cc @renatonlima @rvalyi

**Comment by rvalyi** [comment]
@pedrobaeza @mileo I'll squash the commits.
One reason why we broke down the commits so much is because many people are working on this in parallel or depending on this for further developments so we shared anything we could as quickly as possible. But no problem we can now squash some commits.

**Comment by rvalyi** [comment]
superseeded by https://github.com/OCA/account-fiscal-rule/pull/39 where I squashed 5 commits in @renatonlima work.

**Pull request closed without merging**
