### PR TITLE
port of fiscal classification system by @renatonlima + upstream test fixes by @mileo

### PR DESCRIPTION
**Pull request by rvalyi**
this is https://github.com/OCA/account-fiscal-rule/pull/38 with 5 @renatonlima commits squashed as requested by @pedrobaeza 

I screwed the original PR branch when doing the rebase a few minutes ago but the analysis can still be found here:
https://github.com/OCA/account-fiscal-rule/pull/35
and here for the tests of the upstream fixes of @legalsylvain refactor https://github.com/OCA/account-fiscal-rule/pull/38

cc @renatonlima @pedrobaeza @danimaribeiro @legalsylvain @mileo

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by renatonlima** [comment]
:+1:

**Comment by pedrobaeza** [comment]
I added the incorrect repo to runbot, but Travis is OK, so I merge.

**Comment by rvalyi** [comment]
@pedrobaeza @mileo thanks for your fast support.

**Comment by mileo** [comment]
:+1:

**Pull request merged**
