### PR TITLE
[16.0] IMP account_product_fiscal_classification : recover classification (or create on the fly) if not set

### PR DESCRIPTION
**Pull request by legalsylvain**
Supersed #435

@bealdav, could you review this one ? 

Note : once approved, we should squash all the commits before merging.

thanks !

### CODE REVIEW

**Comment by legalsylvain** [comment]
ealdav, @mourad-ehm : could you take a look on this one ?

**Comment by legalsylvain** [comment]
@bealdav, @mourad-ehm : could you take a look on this one ?

**Review by bealdav — APPROVED** [review]

**Comment by bealdav** [comment]
> Note : once approved, we should squash all the commits before merging.

Squash by author ?

**Comment by legalsylvain** [comment]
Thanks for your review !

Did you tested or just reviewed ? thanks ! 

> Squash by author ?

Not sure it makes sense. we made a lots of contradictory changes, so I'd be more in favor of squashing in 1 commit.

**Comment by bealdav** [comment]
I've just made code review. 

Ok for squash

**Review by mourad-ehm — APPROVED** [review]
code review

**Comment by legalsylvain** [comment]
Thanks for your review ! 

/ocabot merge minor

**Pull request merged**
