### PR TITLE
[ADD] account_fiscal_position_product

### PR DESCRIPTION
**Pull request by SirTakobi**
Adding a new module to apply fiscal position mapping only when the product configured in the fiscal position matches.

### CODE REVIEW

**Comment by rafaelbn** [comment]
Thanks @SirTakobi , we don't use 12 anymore but interesting to migrate for v15

MT-1619

@legalsylvain what do you think? Tomorrow is fridays 😄

**Comment by legalsylvain** [comment]
Hi. could you provide a use case. not sure to understand why the feature is proposed ? thanks !

**Comment by SirTakobi** [comment]
> Hi. could you provide a use case. not sure to understand why the feature is proposed ? thanks !

Thanks for having a look!
In our use-case, the customer has purchased a vending machine in the past; so when we are selling to them products for the vending machine, only those products must have a different tax applied.

With this module, we can create a fiscal position to be assigned to all those customers that have purchased a vending machine; in the fiscal position we configure the products for the vending machine.
When these configured customers purchase the products for the vending machine, the tax configured in the fiscal position is applied.
When these configured customers purchase other products, the standard tax is applied.
When other customers purchase any product, the standard tax is applied.

**Comment by rafaelbn** [comment]
Hello @SirTakobi ,

Sometimes, a short video, animation or screed-shoots help 😄 

Best regards!

**Comment by SirTakobi** [comment]
> Hello @SirTakobi ,
> 
> Sometimes, a short video, animation or screed-shoots help smile
> 
> Best regards!

Thanks, I dare say they are always useful!
But they also take more time, and I thought that the module is clear enough as is.
Do you have any suggestion on what I should clarify in the README or the unit tests?

**Comment by rafaelbn** [comment]
Hello @SirTakobi  😄 

I have tested and recorded a [video](https://www.loom.com/share/c517dd6357f340f7afd8c2fd10872e3b) but I don't understand the need. Obviously is our need! I don't block anything at all 😃 just I don't understand that fiscal rules.

> With this module, we can create a fiscal position to be assigned to all those customers that have purchased a vending machine; in the fiscal position we configure the products for the vending machine.
When these configured customers purchase the products for the vending machine, the tax configured in the fiscal position is applied.
When these configured customers purchase other products, the standard tax is applied.
When other customers purchase any product, the standard tax is applied.

Each product has its own tax, so for the same fiscal position in the customer you can have different taxed with out this module.

Don't worry!

Any case the module name for me is more like

`account_fiscal_position_tax_mapping_by_product`

😉 

Best regards!

**Comment by SirTakobi** [comment]
Thanks a lot for your time! I have seen the video and thanked you over there too :smile:

About the functional aspect of the module, I have forwarded your doubts to someone more functional than me, they will hopefully give you a better explanation.

> Any case the module name for me is more like
>
> `account_fiscal_position_tax_mapping_by_product`

That would work too, but it's a bit too long for my tastes; for now I'd prefer to keep it as is.

**Comment by rafaelbn** [comment]
OK!

`account_fiscal_position_tax_by_product` ?

The name of module as is maybe misunderstand. Up to you!

**Comment by mrcast** [comment]
> Hello @SirTakobi smile
> 
> I have tested and recorded a [video](https://www.loom.com/share/c517dd6357f340f7afd8c2fd10872e3b) but I don't understand the need. Obviously is our need! I don't block anything at all smiley just I don't understand that fiscal rules.
> 
> > With this module, we can create a fiscal position to be assigned to all those customers that have purchased a vending machine; in the fiscal position we configure the products for the vending machine.
> > When these configured customers purchase the products for the vending machine, the tax configured in the fiscal position is applied.
> > When these configured customers purchase other products, the standard tax is applied.
> > When other customers purchase any product, the standard tax is applied.
> 
> Each product has its own tax, so for the same fiscal position in the customer you can have different taxed with out this module.
> 
> Don't worry!
> 
> Any case the module name for me is more like
> 
> `account_fiscal_position_tax_mapping_by_product`
> 
> wink
> 
> Best regards!

Dear @rafaelbn,

the need is to switch tax,  based on fiscal positions, only for the products indicated in the fiscal position mapping.
So, in the sale order, we can have order lines with the standard taxes and order lines with the new taxes.
Here a link to a [video](https://drive.google.com/file/d/1Q9q7hd-dZajEkZuovzy5XZS5XI4Q2_rO/view?usp=share_link).

Best regards,
Mario

**Comment by elvise** [comment]
Hi @SirTakobi can you rebase ?

**Comment by SirTakobi** [comment]
> Hi @SirTakobi can you rebase ?

Done

**Pull request closed without merging**
