### PR TITLE
[15.0] [MIG] account_fiscal_position_autodetect_optional_vies: Migration to 15.0

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
Standard migration

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@HaraldPanten @ValentinVinagre

**Comment by Jesarregui** [comment]
LGTM

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Review by Jesarregui — APPROVED** [review]
LGTM

**Comment by HaraldPanten** [comment]
@pedrobaeza I'll merge this one if it's OK for you. Your team is the original author

**Comment by pedrobaeza** [comment]
Go on!

**Comment by HaraldPanten** [comment]
/ocabot migration account_fiscal_position_autodetect_optional_vies

**Pull request merged**
