### PR TITLE
[17.0] [MIG] account_avatax_exemption

### PR DESCRIPTION
**Pull request by Nikul-OSI**

### CODE REVIEW

**Comment by Nikul-OSI** [comment]
@atchuthan @dreispt Can you please take a look?

**Review by dreispt — APPROVED** [review]
Technical review, no tests.

**Comment by atchuthan** [comment]
@Nikul-OSI @dreispt We found few issues and added it as PR at https://github.com/ursais/account-fiscal-rule/pull/42. Please add these changes. Thanks

**Comment by dnplkndll** [comment]
@kobros-tech please note this. 

> @Nikul-OSI @dreispt We found few issues and added it as PR at [ursais#42](https://github.com/ursais/account-fiscal-rule/pull/42). Please add these changes. Thanks

**Pull request closed without merging**
