### PR TITLE
[14.0][IMP] account_fiscal_position_partner_type: FP with empty FP Type should apply to any Partner type

### LINKED ISSUE #254: account_fiscal_position_partner_type: suprising behavior on Fiscal Positions
I would expect that a Fiscal Position with empty Fiscal Position Type would apply to any Partner.
I should be able to create a single FP "National Customers", that applies both to B2B and B2C.

Right now this doesn't work.
I need to instead have at least two FPs, duplicates except for the FP Type field: one for B2C and another for B2C.

I would like to change this, and allow an FP with no FP Type set to be applicable to Partners with any FP Type assigned to the,

Thoughts? @pedrobaeza @HaraldPanten @ValentinVinagre

### PR DESCRIPTION
**Pull request by dreispt**
Closes https://github.com/OCA/account-fiscal-rule/issues/254

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I think this is not needed. If you don't fill the fiscal position type, no context is passed, so the query expression is not modified and no filter is done.

**Comment by dreispt** [comment]
@pedrobaeza I just revisited the discussion on this:

> If I don't remember bad, not filling the type on the fiscal position means to not check the type of the partner, so that sounds exactly what you want to achieve. You haven't indicated the Odoo version though.

Right now the above is not true - the Partner Type is still checked if unset on the FP.
This change allows for the Partner Type to not be checked when not set in the FP.

Am I misunderstanding this?

**Comment by pedrobaeza** [comment]
The solution to your problem is to set a default value for `fiscal_position_type`. Both design decisions (current one and the one you propose) has its flaws and advantages, but the current one was chosen for maximizing the compatibility: if nothing is selected, nothing from standard is changed. cc @HaraldPanten

**Comment by HaraldPanten** [comment]
> The solution to your problem is to set a default value for `fiscal_position_type`. Both design decisions (current one and the one you propose) has its flaws and advantages, but the current one was chosen for maximizing the compatibility: if nothing is selected, nothing from standard is changed. cc @HaraldPanten

If I remember well, it works as you say.

**Pull request closed without merging**
