### PR TITLE
[IMP] installation of module

### PR DESCRIPTION
**Pull request by legalsylvain**
this PR reduce the time of installation of the module that can be big in an huge database, creating massively product_fiscal_classification.

### CODE REVIEW

**Comment by legalsylvain** [comment]
@rvalyi, could you take a look. this PR reduce a lot time installation. regards.

**Comment by legalsylvain** [comment]
ping @rvalyi

**Comment by legalsylvain** [comment]
Closing, due to inactivity. Feel free to reuse this work.

regards.

**Comment by rvalyi** [comment]
@legalsylvain sorry I missed it. Will try to have a look and tell you.

**Comment by legalsylvain** [comment]
OK. I reopened the PR and fixed the conflict. Is it this PR OK for you ?

regards.

**Comment by legalsylvain** [comment]
and now ;-) ?

**Comment by legalsylvain** [comment]
Closing for lake of review.

**Pull request closed without merging**
