### PR TITLE
[14.0] [FIX] Improved the account_avatax module code.

### PR DESCRIPTION
**Pull request by Chandresh-OSI**

### CODE REVIEW

**Review by dreispt — APPROVED** [review]
Did functional tests and works as expected.

**Comment by metaminux** [comment]
Hi @Chandresh-OSI and @dreispt 

Sorry to put a comment here 6 months after merging, but with this commit, there is no more check on the line price_unit, so having 2 lines with same product and quantity but different prices is messing the line lookup...

Do I miss something here ? Why removing these lines at first point ?

I would like some explanation before creating a new issue with clear example.

Thanks,

**Comment by dreispt** [comment]
@metaminux Don't be sorry, that's part of continuous improvement.
I see your point, that case wasn't verified (and we kind of miss automated tests).
Can you submit a fix please?

**Pull request merged**
