### PR TITLE
[13.0][IMP] account_fiscal_position_rule: add navigation from fiscal position to rules

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
Also update label for field use_sale to be aligned with the other use_* fields

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Code review, LGTM :+1:

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM 👍🏽

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LG

**Pull request merged**
