### PR TITLE
[FIX] account_avatax: Void transaction from posted status

### PR DESCRIPTION
**Pull request by atchuthan**
There was an error with sending void transaction and corrected it now.

cc: @SodexisTeam @dreispt

### CODE REVIEW

**Comment by dreispt** [comment]
Thanks, can you fix pre-commit please?

**Comment by atchuthan** [comment]
> Thanks, can you fix pre-commit please?

Done pre-commit

**Review by dreispt — APPROVED** [review]
The change seems functionally equivalent to the old code, so I'm not sure what is being fixed exactly. But I see no reason to not merge.

**Pull request merged**
