### PR TITLE
12.0 IMP prd_fisc_classif: track change on product model

### PR DESCRIPTION
**Pull request by bealdav**
cc @legalsylvain @hparfr @florian-dacosta

### CODE REVIEW

**Review by dreispt — APPROVED** [review]

**Review by PierrickBrun — APPROVED** [review]

**Review by legalsylvain — CHANGES_REQUESTED** [review]
I dont think it should be done in main module but in custom one. AFAIK, taxes changes are not tracked in Odoo core. I dont see why this field shoud be tracked and not all the others.
Don-t you think ?

**Comment by bealdav** [comment]
Thanks for the review

> I dont see why this field shoud be tracked and not all the others.

Because it have a direct impact on a legal feature in case of sharing catalog in multi company: tax in invoicing and it's very critical to track changes on it. But if on your use case it's useless, please close the PR, i'll add a custom for it. Thanks

**Comment by PierrickBrun** [comment]
> I dont think it should be done in main module but in custom one. AFAIK, taxes changes are not tracked in Odoo core. I dont see why this field shoud be tracked and not all the others.
> Don-t you think ?

That's a good point but IMO this module exists to mitigate tax errors, so this should be a nice addition to have the tracking.

**Review by legalsylvain — APPROVED** [review]
Make sense. Thanks for the explanation.

**Review by florian-dacosta — APPROVED** [review]

**Review by hparfr — APPROVED** [review]

**Review by mourad-ehm — APPROVED** [review]

**Review by rvalyi — APPROVED** [review]

**Comment by legalsylvain** [comment]
7 approvals ! it's a plebiscite

**Pull request merged**
