### PR TITLE
[10.0][MIG]l10n_eu_oss

### PR DESCRIPTION
**Pull request by manuelregidor**
Backport to v10.

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by HaraldPanten — APPROVED** [review]
I could reproduce some "easy path" use cases in runboat, and it's working fine for me.

@manuelregidor could you change your commit message? Normally we should put [MIG] instead of [BCK]. Shouldn't we, @OCA/accounting-maintainers ?

**Comment by HaraldPanten** [comment]
Fast tracking, as we are (probably) the only partner supporting that for V10 and all checks are green.

We'll be using that in a production environment, so... we'll take care if there are some issues.

**Pull request merged**
