### PR TITLE
[14.0] [MIG] account_fiscal_position_autodetect_optional_vies: Migration to 14.0

### PR DESCRIPTION
**Pull request by Tisho99**
Migration from 15.0 to 14.0

T-6135

### CODE REVIEW

**Comment by Tisho99** [comment]
@ValentinVinagre @HaraldPanten

**Comment by HaraldPanten** [comment]
/ocabot migration account_fiscal_position_autodetect_optional_vies

**Comment by ValentinVinagre** [comment]
@Jesarregui

**Review by Jesarregui — APPROVED** [review]
Functional Review: LGTM

**Comment by Jesarregui** [comment]
@ValentinVinagre Could you do a technical review?

**Review by HaraldPanten — APPROVED** [review]

**Review by manuelregidor — APPROVED** [review]
Technical review. LGTM

**Pull request merged**
