### PR TITLE
[14.0][FIX] l10n_eu_oss: Luxembourg VAT rate changed from 17% to 16%

### LINKED ISSUE #365: [All versions] L10n EU OSS : Luxemburg taxes updated
There is a tax difference for Luxembourg.

The VAT rates that will apply in Luxembourg from January 2023:
Standard VAT rate: 16% instead of 17%.
Intermediate VAT rate: 13% instead of 14%.
Reduced VAT rate: 7% instead of 8%.

Now use 17%, 14% and 8%

### PR DESCRIPTION
**Pull request by dreispt**
Closes #365 (for 14.0)

### CODE REVIEW

**Comment by dreispt** [comment]
@josepmy

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by dreispt** [comment]
Hello, can this be merged?

**Review by sergiocorato — APPROVED** [review]

**Pull request merged**
