### PR TITLE
Fiscal classification readme

### PR DESCRIPTION
**Pull request by EBII**
Update index.html 
update readme/*rst file with img path

restore initial Readme template

### CODE REVIEW

**Review by dreispt — CHANGES_REQUESTED** [review]
The changes files are automatically generated from the fragments in `/readme`, so there is little point in these changes.

**Comment by legalsylvain** [comment]
hi @EBII. Could you reduce your PR, removing changes in readme.rst and index.html file ? 

thanks !

**Comment by dreispt** [comment]
@legalsylvain Actually, I see now a lot of PRs with the same pattern, because precommit hooks automatically generate the README.
So I must say we shouldn't mind about that.

**Review by dreispt — APPROVED** [review]

**Comment by legalsylvain** [comment]
Hi @dreispt. Are you sure ? I don't see it in the pre-commit file of repo I checked ?

Anyway, I see it as a problem if precommit update such files, because it will generate a lot of conflict. (like here, that should be solved, @EBII )

**Comment by dreispt** [comment]
@EBII To update the README, please use the fragments in the `/readme` subdirectory.
You're welcome to propose a new PR.

**Pull request closed without merging**
