### PR TITLE
[13.0][FIX] Partner Exemption Code configuration

### PR DESCRIPTION
**Pull request by bodedra**
Steps to reproduce:

- Change name on existing exemption code
- Go to apps and upgrade "account_avatax" module
- It will wipe out changes that we made previously.

This PR will fix it.

### CODE REVIEW

**Comment by bodedra** [comment]
@dreispt @atchuthan

**Comment by atchuthan** [comment]
@bodedra 
we are using the code field of exemption.code model as EntityUseCode for the transaction, so I don't think we need to change these configuration data with noupdate="1".
If some customer changed the code wrongly, then the info sent to Avatax transaction will be wrong.

**Comment by dreispt** [comment]
@bodedra I feel @atchuthan has a point.
These are Avatax provided codes, whet is the use case to change them?

**Comment by bodedra** [comment]
@atchuthan @dreispt Code is fine. But in my case, they have different name for same code.

**Comment by atchuthan** [comment]
@bodedra 
If the name you are going to change is a standard name, we can change the name of the exemption.code itself in the data XML file, right?

**Comment by dreispt** [comment]
@atchuthan We should not edit the module's data file directly. I'm OK with adding the noupdate. Edits there are at the customer risk, but so is tax configuration in general.

**Review by dreispt — APPROVED** [review]

**Comment by bodedra** [comment]
> @bodedra
> If the name you are going to change is a standard name, we can change the name of the exemption.code itself in the data XML file, right?

@atchuthan We are using submodule structure for OCA module deployment so we never change anything directly.

**Review by atchuthan — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
