### PR TITLE
[14.0][REF] Update dotfiles

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by rafaelbn** [comment]
@dreispt any idea?

**Comment by dreispt** [comment]
Pushed a fix.

**Comment by dreispt** [comment]
I now see `Error: Docker login for 'ghcr.io' failed with exit code 1`
@OCA/community-maintainers Any idea?

**Comment by pedrobaeza** [comment]
Retry. It seems a glitch.

**Comment by rvalyi** [comment]
Yeah we had similar issues with other repos earlier and GitHub reported CI issues https://twitter.com/githubstatus/status/1596159699094732808?t=Vfw2m-DMDLiWPZEUSwKysQ&s=19

**Pull request closed without merging**
