### PR TITLE
[FIX] account_avatax_sale: Field 'is_add_validate' definition not available

### PR DESCRIPTION
**Pull request by SodexisTeam**
Either we should remove the "is_add_validate" field from _onchange_partner_shipping_id or add this field to account.move

### CODE REVIEW

**Comment by dreispt** [comment]
Is that field useful?

**Comment by atchuthan** [comment]
The field is not used in any Avatax API.  Also, this field was hidden in the older version.

**Comment by dreispt** [comment]
If if is not useful, maybe we just just remove it completely.

**Review by dreispt — APPROVED** [review]

**Pull request merged**
