### PR TITLE
[16.0] account_product_fiscal_classification: 2 small changes

### PR DESCRIPTION
**Pull request by alexis-via**
2 small changes:
1) add search view on account.product.fiscal.classification
2) remove translate=True on name field on account.product.fiscal.classification

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Hi @alexis-via. Thanks for the contribution ! 
1. commit about the view :+1: 
2. commit about the translation : 

- I personally don't use this module in a multicompany context. (I mean 1 classification per company no "global classification").
- I personally don't use translation. (all my companies are french).
- I so do what your propose in a "custom module" for the time being ;-) and I plan to port that module in V16 : https://github.com/grap/grap-odoo-custom/blob/12.0/grap_change_translation/models/account_product_fiscal_classification.py#L11

However, do you think it's valid for all the OCA users ? 

On the other hand, In odoo : 
- ``acount.tax`` is not translatable : https://github.com/odoo/odoo/blob/16.0/addons/account/models/account_tax.py#L88
- ``account.tax.group`` is translatable : https://github.com/odoo/odoo/blob/16.0/addons/account/models/account_tax.py#L26

In fact, I don't know if there is real configuration with global classification in a multi country context. @rvalyi, @PierrickBrun : a PoV on that topic ?

**Comment by rvalyi** [comment]
Hello @legalsylvain, I confirm we designed this module for supporting global classification over several companies and we have a use case at Akretion with such a case on v14. It's an important feature I think.

**Comment by legalsylvain** [comment]
I had understood that you had stopped using this module in Brazil? Did I miss something ?

**Pull request merged**
