### PR TITLE
[15.0] [BKP] account_fiscal_position_type

### PR DESCRIPTION
**Pull request by Shide**
**Backport** of `account_fiscal_position_type` (**from v16**, not migration from v12)

Things changed:
- `.mapped` on tests (`test_invoice_fiscal_position_domain` function) returns a full list (don't know why), so casted to set
- `account_type` on demo of  `account.account.template` changed to `user_type_id` and used the proper reference.

MT-1453 @moduon @rafaelbn @legalsylvain

### CODE REVIEW

**Comment by rafaelbn** [comment]
Should we add also this commiit? 

https://github.com/OCA/account-fiscal-rule/pull/333/commits/e82e1c541804130e5403cdc272387fff7517b7fd

**Comment by Shide** [comment]
In the process of migration from v12 to v16, has been removed (check commit message)

**Review by ghost — APPROVED** [review]
Functional review. LGTM!

Screenshot_20230126_082702
Screenshot_20230126_084158
Screenshot_20230126_084244

**Review by fcvalgar — APPROVED** [review]
LGTM.

Thank you @Shide

**Comment by loida-vm** [comment]
Funtional review, LGTM!
In the video I have tested the fiscal position configured for sales and it does the correct usage https://www.loom.com/share/910e2f0eef704e83a7d564f0399244e2

**Review by loida-vm — APPROVED** [review]

**Comment by rafaelbn** [comment]
Hello @legalsylvain could you please give your bless? 😄 

Just check https://github.com/OCA/account-fiscal-rule/pull/349#issuecomment-1404281516

**Review by rafaelbn — APPROVED** [review]
Thank you! 👍

**Comment by rafaelbn** [comment]
@Shide fails pre-commit

**Comment by dreispt** [comment]
It seems to be a pre-commit tooling issue: 
```
RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
```
https://github.com/OCA/account-fiscal-rule/actions/runs/4049280426/jobs/6965466717#step:7:77

**Comment by yajo** [comment]
I pushed the fix. Related to https://github.com/OCA/oca-addons-repo-template/pull/184.

**Pull request merged**
