### PR TITLE
[14.0][ADD] account_avatax_exemption

### PR DESCRIPTION
**Pull request by SodexisTeam**
Needs 14.0 migrate of account_avatax and account_avatax_sale
Depends on https://github.com/OCA/account-fiscal-rule/pull/150

@stephankeller @dreispt @dnplkndll @max3903

### CODE REVIEW

**Review by odoo-sh — APPROVED** [review]
@dreispt Daniel, this has been in production for Kencove for about two months now with no issue, so can you please approve it?  Thanks.

**Review by dreispt — COMMENTED** [review]
Can you please add a readme subdirectory with text fragments, on both modules, so that a nice readme is automatically generated later?

**Comment by atchuthan** [comment]
@dreispt 
Added basic readme.rst using maintainer-tools.
We will update the readme.rst later in more detail with a new PR.

**Comment by atchuthan** [comment]
rebased the commits with latest 14.0 branch

**Comment by atchuthan** [comment]
Runbot and pre-commit are green now!!

**Review by dreispt — APPROVED** [review]

**Comment by dreispt** [comment]
@atchuthan The `account_avatax_exemption_base` module has a License issue: it is LGPL but depends on AGPL modules.
It needs to be changed to AGPL.

**Pull request merged**
