### PR TITLE
12.0 ref initialize copier template

### PR DESCRIPTION
**Pull request by legalsylvain**
trivial PR
Unlock https://github.com/OCA/account-fiscal-rule/pull/333

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
LGTM 👍

**Comment by rafaelbn** [comment]
@legalsylvain can you merge this? Who can help here?

**Comment by legalsylvain** [comment]
Hi. I don't have write access to this repo.  @OCA/accounting-maintainers maybe ?

**Review by rvalyi — APPROVED** [review]

**Pull request merged**
