### PR TITLE
[15.0][MIG]l10n_eu_oss

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration
Depends on https://github.com/OCA/account-fiscal-rule/pull/252

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@manuelregidor could you make a rebase please?

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by ValentinVinagre** [comment]
@HaraldPanten

**Review by HaraldPanten — APPROVED** [review]
Wizard is working fine for creating taxes and fiscal positions as well.

LGTM

**Comment by emagdalenaC2i** [comment]
@manuelregidor Odoo 15 already has a module called l10n_eu_oss.
Won't this create some issues?

**Comment by HaraldPanten** [comment]
That's right, seems that they made changes to their original module for OSS.

Maybe we should rename the module to l10n_eu_oss_oca

@pedrobaeza @ValentinVinagre WDYT?

**Comment by emagdalenaC2i** [comment]
I did not check the Odoo module, I have just seen that it is called the same

**Comment by HaraldPanten** [comment]
It seems that they improved their old system for applying OSS taxes, but I think they still not check the partner type (company/final customer) so... I still don't see an easy way to map the taxes according the customer type.

On the other hand, I'm not sure if they mapped the taxes correctly. For example, they do not consider the super reduced VAT for Spain. It's not the most common for distance sales, maybe, but it does exist.

IMO, we still need this module for V15 in OCA. So... renaming is the best option I think.

**Comment by ValentinVinagre** [comment]
> It seems that they improved their old system for applying OSS taxes, but I think they still not check the partner type (company/final customer) so... I still don't see an easy way to map the taxes according the customer type.
> 
> On the other hand, I'm not sure if they mapped the taxes correctly. For example, they do not consider the super reduced VAT for Spain. It's not the most common for distance sales, maybe, but it does exist.
> 
> IMO, we still need this module for V15 in OCA. So... renaming is the best option I think.

I agree with @HaraldPanten

**Comment by pedrobaeza** [comment]
But if the name is exactly the same, we should rename it.

**Comment by ValentinVinagre** [comment]
> But if the name is exactly the same, we should rename it.

How should we make the name change? With an imp? the name could be: l10n_eu_oss_oca

**Comment by pedrobaeza** [comment]
It's too late for doing things OK, but let's rename it on a new PR, and on v16, we need to extract whole commit history and do the renaming backwards.

**Pull request merged**
