### PR TITLE
[MIG] [12.0] mig account fiscal position partner type

### PR DESCRIPTION
**Pull request by angelmoya**
Issue: OCA/l10n-spain#1718

### CODE REVIEW

**Review by colmeirin — APPROVED** [review]
Functional review in clean v12, works great!

**Review by jesusVMayor — APPROVED** [review]
LGTM

**Review by HaraldPanten — APPROVED** [review]
@ValentinVinagre could you do a technical review, please?

**Review by rlizana — APPROVED** [review]
LGTM :+1:

**Pull request merged**
