### PR TITLE
[FIX] account_avatax: Update taxes only for Draft Invoices

### PR DESCRIPTION
**Pull request by atchuthan**
Minor fix: Only update taxes with Avatax API for Draft invoices.

### CODE REVIEW

**Review by dreispt — APPROVED** [review]
This looks good, and it could go further: the Server Action should go away, and the filter should be in the ORM code.

**Comment by atchuthan** [comment]
I got your point, I made changes such that either condition of state == 'draft' or commit==True if available.  Because commit=True will be sent after the Invoice is validated.

**Comment by dreispt** [comment]
Thank you, this is an improvement, and achieves the goal of preventing of accident.
To also protect against ill intended RPC calls a small refactoring would be needed, but I guess that is out of scope for this fix.

**Pull request merged**
