### PR TITLE
[13.0][FIX] account_avatax: full refund, closes

### PR DESCRIPTION
**Pull request by bodedra**
This PR contains backport of https://github.com/OCA/account-fiscal-rule/pull/191 and address comment https://github.com/OCA/account-fiscal-rule/pull/191#issuecomment-831391292

### CODE REVIEW

**Comment by dreispt** [comment]
@bodedra Can we have two separate PRs, one for the backport fix, and the otehr for the post() proposed fix?

**Comment by bodedra** [comment]
@dreispt backport PR https://github.com/OCA/account-fiscal-rule/pull/194

**Comment by bodedra** [comment]
@dreispt Both PRs affect same method. So I will propose post() fix once we merge backport. Sounds good?

**Comment by dreispt** [comment]
OK

**Comment by dreispt** [comment]
Regarding the post() fix, it is a bit trickier than that.
The naive solution is to have the first loop use `commit=True` on the Avatax call, and completely remove the second for loop.
This will do the same as the proposed solution, with half the API calls.

Now there is a risk if we do this: what if the Odoo `post()` fails?
The Avatax call was already made, so it is commitetd to Avatax.
But the Odoo invoice is rolled back, as is not stored in the system.
We now have an inconsistency.

The solution is for the second loop to use an API call changing the state of the Avatax draft document to committed, without recomputing taxes, as it is doing now.
I see no reason for the the second Avatax call to compute a different amount ("a penny off"), so there *should* not be a real problem here.
Still, this later implementation seems safer and also more efficient.

**Comment by bodedra** [comment]
If Odoo `post()` fails, we should voided that transaction to Avatax.

**Comment by bodedra** [comment]
I faced issue before, `Entity not found` during reset to draft invoice. It seems Odoo recorded transaction as a Avatax and Avatax doesn't found transaction.  I may be talking about different issue.

**Comment by dreispt** [comment]
That's the symptom, but it usually is caused several Odoo test instances sharing the same Avatax service backend.

To set a document to committed use `avatax_config.commit_transaction(self.name, doc_type)`.
Example: https://github.com/OCA/account-fiscal-rule/blob/14.0/account_avatax/models/account_move.py#L226

**Pull request closed without merging**
