### PR TITLE
[10.0][IMP] account_fiscal_position_rule: Refactoring

### PR DESCRIPTION
**Pull request by renatonlima**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't this already migrated in https://github.com/OCA/account-fiscal-rule/pull/61?

**Comment by renatonlima** [comment]
Hello @pedrobaeza,

In fact, the module is already migrated, I just did a refactoring, I changed commits message and PR title.

**Comment by pedrobaeza** [comment]
I have changed the title to adjust to conventions :wink:

**Review by rvalyi — APPROVED** [review]
LGTM

**Review by mbcosta — APPROVED** [review]

**Pull request merged**
