### PR TITLE
Feature/account fiscal position rule sale migration 8.0

### PR DESCRIPTION
**Pull request by renatonlima**

### CODE REVIEW

**Comment by rvalyi** [comment]
(I just rebased on 8.0 to see where we are with the tests on that one)

**Comment by rvalyi** [comment]
tests passing after the rebase. Pretty well tested in production too so :+1: for me

**Comment by rvalyi** [comment]
ping @mileo @danimaribeiro time for a review?

**Comment by mileo** [comment]
LGTM! :+1:

**Comment by danimaribeiro** [comment]
:+1: 
Just remove empty xml inside security.

**Comment by rvalyi** [comment]
@danimaribeiro I took your considerations into account. Now merging as we have enough approvals. A test would be cool be leaving that for next PR.

**Pull request merged**
