### PR TITLE
11.0 mig l10n eu oss

### PR DESCRIPTION
**Pull request by RodrigoBM**
add cherry pick
#207

Issue: OCA/l10n-spain#1718

### CODE REVIEW

**Comment by HaraldPanten** [comment]
@RodrigoBM could you rebase?

**Comment by RodrigoBM** [comment]
Done

**Comment by RodrigoBM** [comment]
@HaraldPanten Done

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Comment by HaraldPanten** [comment]
As V11 is no longer supported, I'll merge this one for fast tracking. Please, remember to update this module if you detect any issue 👍

**Pull request merged**
