### PR TITLE
Added company_id onchange to auto complete country and state

### PR DESCRIPTION
**Pull request by renatonlima**

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1:

**Comment by rvalyi** [comment]
@renatonlima please rebase. I fixed the files layout, rebase is required now.

**Comment by rvalyi** [comment]
rebased. cc @mileo @danimar @max3903 @mbcosta @sebastienbeau

**Comment by mbcosta** [comment]
:+1:

**Comment by sebastienbeau** [comment]
Ok for me :+1: code review, no test

**Pull request merged**
