### PR TITLE
anticipate OCA file layout to ease 8 <-> 9 ports

### PR DESCRIPTION
**Pull request by rvalyi**

### CODE REVIEW

**Comment by lmignon** [comment]
:+1:  Thank you @rvalyi for anticipating!!! (Code review no test)

**Comment by pedrobaeza** [comment]
Well, OCA file layout tells about models and views (in plural): https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#directories

**Comment by rvalyi** [comment]
@pedrobaeza my bad, unsure I looked at https://github.com/OCA/account-fiscal-rule/tree/8.0/account_fiscal_position_rule_purchase and https://github.com/OCA/account-fiscal-rule/tree/8.0/account_fiscal_position_rule_sale where it was wrong as well... At least that the only two places where it's wrong I could find. Fixing them all...

**Comment by rvalyi** [comment]
@pedrobaeza @lmignon what about that one?
cc @renatonlima @mileo @danimaribeiro

**Comment by mileo** [comment]
:+1: LGTM

**Comment by danimaribeiro** [comment]
There are few warnings in the build, like:
"Missing ./README.rst"

I don't know when those will leave beta status ?
Is it worth fixing now?

**Comment by pedrobaeza** [comment]
Well, if you do, they're welcome, but for v9 there are no plans for making blocking issues.

**Comment by rvalyi** [comment]
I can push some README templates in the PR. As for actually filling them with useful doc, I think we can leave that for later...

**Comment by pedrobaeza** [comment]
Well, I prefer then that you do it at once. Make progressive PRs with one README each time, but with the full format

**Comment by rvalyi** [comment]
@pedrobaeza so you approved we merge that one this way?

**Comment by pedrobaeza** [comment]
Yes, I approve it and merge it :wink:

**Pull request merged**
